# Generated by Django 6.1.1 on 2026-09-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterField(
            model_name='group',
            name='heading',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='index_file',
            name='heading',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='sub_group',
            name='heading',
            field=models.CharField(max_length=70),
        ),
    ]
