# Generated by Django 6.0.6 on 2026-06-29 02:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_group_root_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='root_group',
            new_name='Group',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
    ]
