# Generated by Django 6.0.6 on 2026-07-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_create_superuser'),
        ('App', '0003_rename_root_group_group_alter_group_options'),
    ]

    operations = [
    ]
