# Generated by Django 6.0.6 on 2026-07-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_merge_20260704_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='heading',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='index_file',
            name='heading',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='sub_group',
            name='heading',
            field=models.CharField(max_length=70),
        ),
    ]
